server:
  port: 8080
spring:
  application:
    name: web-start
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/quick?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
          username: root
          password:

  redis:
    # Redis 单机实例
    database: 0
    host: localhost
    port: 6379
    password:

mybatis:
  type-aliases-packege: top.soulblack.foodie.pojo  # 所有pojo类所在包路径
  mapper-locations: classpath:mapper/*.xml         # mapper映射文件

feign:
  httpclient:
    enabled: false
    max-connections: 200 # 连接池最大闲置数，缺省值200
    time-to-live: 900 # 连接最大闲置时间，单位为秒
  okhttp:
    enabled: true
  client:
    config:
      default: #服务名， 填写default为所有服务，或者指定服务，例如quick-web，一下两个条件必须同时设置，优先级更高
        connectTimeout: 10000 # 连接超时时间10秒
        readTimeout: 20000 # 读取超时时间20秒

redisson:
  enable: true

logging:
  level:
    top.soulblack.quick: debug
